### ISSUE TITLE
theme variants

### ISSUE THREAD

**Issue by incantatem1** [Quinta0/Lavender-Mist#1]
would it be possible to put all of these into a style settings file to make them selectable theme variants? (this is possibly too much to ask for since you seem really new at theme making, but i think it would be great to have them selectable like that instead of having to install each one individually.)

**Comment by Quinta0** [comment]
Absolutely! Next time i will get back to the theming i will keep that in mind.

**Comment by Quinta0** [comment]
Mind if i close the issue or do you want me to keep it open ?

**Comment by incantatem1** [comment]
you can close it
